[theme]
primaryColor = "#e82127"  # Tesla Red
backgroundColor = "#121212"  # Dark background
secondaryBackgroundColor = "#333333"  # Subtle accent for panels
textColor = "#f5f5f5"  # Light text for dark background
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
